# Generated by Django 5.2.7 on 2025-10-17 18:11

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PositionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.UUIDField(db_index=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device_id', 'recorded_at'], name='home_positi_device__3434b2_idx')],
            },
        ),
    ]
